### ISSUE TITLE
check buttons invisible

### ISSUE THREAD

**Issue by MasterGeekMX** [solsticeman/NiteBrite-Theme#1]
I downloaded the theme from the repo and installed it on my debian box (10 Buster, xfce 4.12.2), but the checkbox buttons are invisible.
I tried it to fix myself editing gtk.css, but I'm a total novice in terms of css, let alone gkt themeing.

Here is a screenshot of `gtk3-widget-factory` of the theme. Notice how the checkbox are hightihter when the mouse hovers it, but non of them are visible:

![Captura 2020-11-13 18-46-03](https://user-images.githubusercontent.com/10291989/99133767-e9c78080-25e0-11eb-84a6-86a4bc10381a.png)

**Comment by solsticeman** [comment]
The symbolic links are indeed missing in the GTK3 folders. This product is no longer maintained and has being replaced with "NiteBrite" themes, with two additional color versions. Sorry for not addressing sooner and for the inconvenience. This issue can be fixed by copying the two shortcuts from another theme into the GTK3.0 folder. Moving the theme from one OS to another without compressing the files causes this issue.
